### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by Everthings** [RawanAlharbi/SenseView#2]
Importing and then exporting from csv labels throws the following error (Note: I slightly modified the code import/export from the directory containing the images instead of the output folder):

```
Traceback (most recent call last):
  File "SenseView.py", line 213, in export_labels
    self.time.iloc[self.labels].to_csv(self.directory + "/hand_labels_"+save_timestamp+".csv", header=True)
  File "/home/andyxu/SenseView/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1424, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/andyxu/SenseView/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 2148, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/home/andyxu/SenseView/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 2133, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds")
IndexError: positional indexers are out-of-bounds
Aborted (core dumped)
```

export/import works fine on their own.

**Comment by Everthings** [comment]
Solved by changing `header=None` in import_labels() to `header=0`.
